[versions]
agp = "8.7.2"
facebookAndroidSdk = "[LATEST_VERSION]"
firebaseAuthVersion = "23.1.0"
firebaseBom = "33.6.0"
googleFirebaseAnalytics = "22.1.2"
googleFirebaseAuth = "21.0.6"
googleFirebaseDatabase = "21.0.0"
googlePlayServicesAuth = "20.1.0"
kotlin = "1.9.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
googleGmsGoogleServices = "4.4.2"
firebaseAuth = "23.1.0"
playServicesAuth = "21.2.0"
playServicesAuthVersion = "20.5.0"
firebaseDatabase = "21.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
facebook-android-sdk = { module = "com.facebook.android:facebook-android-sdk", version.ref = "facebookAndroidSdk" }
firebase-auth-v2106 = { module = "com.google.firebase:firebase-auth", version.ref = "googleFirebaseAuth" }
firebase-auth-v2108 = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuthVersion" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-database-v2005 = { module = "com.google.firebase:firebase-database", version.ref = "googleFirebaseDatabase" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "googleFirebaseAnalytics" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
play-services-auth-v2010 = { module = "com.google.android.gms:play-services-auth", version.ref = "googlePlayServicesAuth" }
play-services-auth-v2050 = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuthVersion" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

